database:
    host: "localhost"
    port: 5432
    user: "user"
    password: "130197"
    name: "orders"
stan:
    host: "localhost"
    port: 4222
    —ÅlusterID: "test-cluster"
    clientID: "clientOrder"